import json
import time
import argparse
import os
import re
from typing import Tuple, Dict, Any, List
import hmmalign._core as hmm

def calculate_stats(cigar: str) -> Tuple[float, int, int, int, int]:
    """
    Parses a CIGAR string to calculate alignment identity and indel metrics.

    Args:
        cigar: The CIGAR string generated by the alignment engine.

    Returns:
        A tuple containing:
            - identity (float): Percent identity (matches / total aligned columns).
            - matches (int): Total number of 'M' operations.
            - ins (int): Total number of 'I' operations.
            - dels (int): Total number of 'D' operations.
            - soft (int): Total number of 'S' operations.
    """
    if not cigar:
        return 0.0, 0, 0, 0, 0
    
    tokens: List[Tuple[str, str]] = re.findall(r'(\d+)([MIDSH])', cigar)
    m = sum(int(n) for n, op in tokens if op == 'M')
    i = sum(int(n) for n, op in tokens if op == 'I')
    d = sum(int(n) for n, op in tokens if op == 'D')
    s = sum(int(n) for n, op in tokens if op == 'S')
    
    # Identity is matches over total alignment columns (M + I + D)
    identity = (m / (m + i + d)) * 100 if (m + i + d) > 0 else 0.0
    return identity, m, i, d, s

def load_fasta(path: str) -> Tuple[str, str]:
    """
    Loads a FASTA file and extracts the first record's header and sequence.

    Args:
        path: Filesystem path to the .fa or .fasta file.

    Returns:
        A tuple of (header, sequence). Returns ("Unknown", "") if loading fails.
    """
    try:
        with open(path, 'r') as f:
            lines = f.readlines()
            if not lines: return "Unknown", ""
            header = lines[0].strip().lstrip('>')
            seq = "".join(line.strip() for line in lines[1:]).upper()
            return header, seq
    except Exception as e:
        print(f"Error loading FASTA: {e}")
        return "Unknown", ""

def write_sam(
    output_path: str, 
    read_id: str, 
    ref_id: str, 
    cigar: str, 
    seq: str, 
    score: float, 
    ref_len: int
) -> None:
    """
    Writes alignment results to a standard SAM file format.

    Args:
        output_path: Path to save the .sam file.
        read_id: Name of the query/sample sequence.
        ref_id: Name of the reference sequence.
        cigar: The CIGAR alignment string.
        seq: The actual nucleotide sequence of the query.
        score: The Viterbi alignment score.
        ref_len: Length of the reference sequence (required for SAM @SQ header).
    """
    header = f"@HD\tVN:1.6\tSO:unsorted\n@SQ\tSN:{ref_id}\tLN:{ref_len}\n"
    # AS:f: is the optional tag for the float alignment score
    record = f"{read_id}\t0\t{ref_id}\t1\t60\t{cigar}\t*\t0\t0\t{seq}\t*\tAS:f:{score}\n"
    with open(output_path, "w") as f:
        f.write(header + record)

def get_report(
    ref_id: str, 
    ref_seq: str, 
    read_id: str, 
    read_seq: str, 
    identity: float, 
    matches: int, 
    ins: int, 
    dels: int, 
    soft: int, 
    result: Any,
    start_time: float, 
    end_time: float, 
    sam_path: str
) -> None:
    """
    Prints a formatted ASCII summary of the alignment results to the console.
    """
    latency_ms = (end_time - start_time) * 1000
    print(f"\n" + "═"*60)
    print(f" 🧬 HMMAlign Summary Statistics")
    print(f" " + "─"*58)
    print(f" Reference:  {ref_id} ({len(ref_seq)} bp)")
    print(f" Query:      {read_id} ({len(read_seq)} bp)")
    print(f" Status:     Success")
    print(f" " + "─"*58)
    print(f" Identity:    {identity:.2f}%")
    print(f" Matches:     {matches:,} bp")
    print(f" Indels:      {ins:,} Ins / {dels:,} Del")
    print(f" Soft-clips:  {soft:,} bp")
    print(f" Score:       {result.score:.2f}")
    print(f" Latency:     {latency_ms:.2f} ms")
    print(f" " + "─"*58)
    print(f" Result:      {sam_path}")
    print("═"*60 + "\n")

def main() -> None:
    """
    Main entry point for the HMMAlign pipeline. Orchestrates configuration loading,
    C++ kernel execution, statistics calculation, and output generation.
    """
    parser = argparse.ArgumentParser(description="HMM-based sequence alignment tool.")
    parser.add_argument("--input", required=True, help="Path to input.json")
    parser.add_argument("--config", required=True, help="Path to config.json")
    args = parser.parse_args()

    # Load configurations
    with open(args.config, "r") as f: config: Dict[str, Any] = json.load(f)
    with open(args.input, "r") as f: inputs: Dict[str, Any] = json.load(f)

    # Load data
    ref_header, ref_seq = load_fasta(inputs["data"]["reference"])
    read_header, read_seq = load_fasta(inputs["data"]["sample"])

    # Map parameters to C++ struct
    params = hmm.ModelParams()
    p = config.get("parameters", {})
    for key, val in p.items():
        if hasattr(params, key): 
            setattr(params, key, val)

    # Execute alignment
    buf = hmm.AlignmentBuffer()
    start_time = time.perf_counter()
    result = hmm.viterbi_align_buffered(read_seq, ref_seq, params, buf)
    end_time = time.perf_counter()

    # Post-processing
    identity, matches, ins, dels, soft = calculate_stats(result.path)

    # Path management
    out_dir = inputs["execution"].get("output_dir", "./results")
    out_name = inputs["execution"].get("output_file", "alignment.sam")
    os.makedirs(out_dir, exist_ok=True)
    sam_path = os.path.join(out_dir, out_name)
    
    # ID cleaning
    read_id = read_header.split()[0]
    ref_id = ref_header.split()[0]

    # Outputs
    write_sam(sam_path, read_id, ref_id, result.path, read_seq, result.score, len(ref_seq))
    get_report(
        ref_id, ref_seq, read_id, read_seq, identity, matches, ins, dels, soft, result,
        start_time, end_time, sam_path
    )

if __name__ == "__main__":
    main()